---
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  labels:
    role: alert-rules
    app: {{ .Values.prometheus_rule_selector_app }}
    release: {{ .Values.prometheus_rule_selector_release }}
    instance: {{ .Values.fullnameOverride }}-cassandra-rules
  name: {{ .Values.fullnameOverride }}-cassandra-rules
  namespace: {{ .Values.namespace }}
spec:
  groups:
  - name: alertrules.appes
    rules:
    - alert: cassandra_node_down_fatal
      annotations:
        message: cassandra_node_down_fatal
        summary: {{`"There are only {{$value}}`}} < {{ .Values.cassandra_server_count }} {{` Cassandra nodes running"`}}
      expr: cassandra_stats{name="org:apache:cassandra:db:storageservice:livenodes"} < {{ .Values.cassandra_server_count }}
      for: 5m
      labels:
        severity: fatal
     - alert: cassandra_test_iops
       annotations:
        message: cassandra_node_down_fatal
        summary: {{`"There are only {{$value}}`}} < 400
      expr: cassandra_stats{cluster="Test Cluster",datacenter="datacenter1",instance="11.5.2.16:8080",job="cassandra-exporter",keyspace="portal",name="org:apache:cassandra:metrics:table:portal:sessions:writelatency:count",table="sessions"} < 400
      for: 5m
      labels:
        severity: fatal
